---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: silly-flight-ingres
  namespace: silly-flights
  annotations:
    kubernetes.io/ingress.class: traefik-external
    link.argocd.argoproj.io/external-link: 'https://flight.nzdev.org/'
spec:
  entryPoints:
    - websecure

  routes:
    - match: Host(`flight.nzdev.org`)
      kind: Rule
      services:
        - name: silly-flight-service
          port: 80
---
